@startuml
skinparam classAttributeIconSize 0

class Job <<PlanningEntity>> {
  +id: String
  +requiredMachineType: String
  +duration: int
  +assignedMachine: Machine <<PlanningVariable>>
  +assignedStartTime: Integer <<PlanningVariable>>
  +orderId: String
  +indexInOrder: int
}

class Machine {
  +id: String
  +type: String
}

Job --> "0..1 " Machine : assigned to >

@enduml
